# Generated by Django 4.0.6 on 2022-07-26 14:17

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('game_id', models.CharField(default=game.models.random_string, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('deck_id', models.CharField(default=game.models.generate_deck, editable=False, max_length=15)),
                ('player_name', models.CharField(max_length=100)),
                ('player_bet', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
