# Generated by Django 4.0.6 on 2022-07-27 15:22

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_game_id_match_match_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_bet',
        ),
        migrations.AlterField(
            model_name='match',
            name='player_name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('hand_id', models.CharField(default=game.models.random_string, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('hand_bet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hand_address', models.CharField(max_length=150)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.match')),
            ],
            options={
                'verbose_name_plural': 'Hands',
            },
        ),
    ]
