# Generated by Django 4.0.6 on 2022-07-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_match_options_remove_match_player_bet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='hand_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
