# Generated by Django 4.0.6 on 2022-07-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_hand_hand_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='hand_stopped',
            field=models.BooleanField(default=False),
        ),
    ]
