# Generated by Django 4.0.6 on 2022-07-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_hand_hand_stopped_hand_hand_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hand',
            old_name='hand_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='hand',
            old_name='hand_bet',
            new_name='bet',
        ),
        migrations.RenameField(
            model_name='hand',
            old_name='hand_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='hand',
            old_name='hand_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='hand',
            old_name='hand_points',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='hand',
            old_name='hand_status',
            new_name='status',
        ),
    ]
