# Generated by Django 4.0.6 on 2022-07-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='prize',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
